sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.1.114
    port: 3306
    database: sky_take_out
    username: usr
    password: 12345678
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-id:
    bucket-name: gargamelzhou
    access-key-secret:
  redis:
    host: 192.168.1.114
    port: 6379
    database: 0
  wechat:
    appid: wx4fb31ef80c4f3506
    secret: e2af73259d369b58d6894523f6ca789a